### ISSUE TITLE
Can you help me in this?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [mataherry/WhatsAppAny#1]
can you help me on https://numbertowhatsapp.bhadoo.net/

https://github.com/ParveenBhadooOfficial/numbertowhatsapp

**Comment by mataherry** [comment]
How can I help?

**Comment by ParveenBhadooOfficial** [comment]
I need to Add country code select system in it. a Select Type of Button to select Country Code but it should not void the link it generates.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by ParveenBhadooOfficial** [comment]
I fixed the space problem but it only works when clicking on the button.

But if we enter space in the number and press enter it creates links like.

https://api.whatsapp.com/send?phone=9197+55665

**Comment by mataherry** [comment]
Try updating the form action url using jquery submit event handler. Also please create this issue in your github project, not mine. Thank you.
